# generated by datamodel-codegen:
#   filename:  chat_data.schema.json

from enum import Enum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class Platform(Enum):
    telegram_html = 'TelegramHTML'
    discord_html = 'DiscordHTML'


class Type(Enum):
    direct = 'Direct'
    group = 'Group'


class Attributes(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    platform: Platform
    chat_name: Annotated[str, Field(alias='chatName')]
    """Name of the chat"""
    type: Type
    participants: list[str]
    file_path: Annotated[str, Field(alias='filePath')]
    """Absolute path to file data was collected from"""


class Type1(Enum):
    text = 'Text'
    media = 'Media'
    system = 'System'


class Context(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    to: int | None
    """Sequence of contextual message"""
    text: str
    """Text of contextual message"""


class Attachment(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    mime: str
    """MIME type of attachment"""
    url: str
    """URL of attachment"""


class Reaction(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str
    """Name of reaction"""
    author: str
    """Author of reaction"""


class Message(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    """Platform provided ID of message"""
    sequence: int
    """Sequence the message was read in"""
    timestamp: str | None
    """Timedate when message was sent"""
    type: Type1
    author: str
    """Sender of message"""
    body: str | None
    """Text contents of message"""
    context: Context | None
    attachments: list[Attachment | None]
    reactions: list[Reaction | None]


class ChatData(BaseModel):
    """An individual chat, could be direct message or group"""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    format_revision: Annotated[int, Field(alias='formatRevision', gt=-1)]
    """Revision count of this schema format (presently 0)"""
    attributes: Attributes
    messages: list[Message | None]
