---
title: Chat data JSON schema diagram
config:
  layout: elk
  theme: neutral
---

flowchart LR
    subgraph main[ ]
        style main fill:none,stroke:none,color:#777
        JSON([JSON Root]) --> formatRevision["formatRevision: Integer"]
            formatRevision --- formatRevision1("Revision count of this schema format (presently 1)")
        JSON([JSON Root]) --> attributes["attributes: Object"]
            attributes --> platform["platform: String"]
                platform --> platform1{{"TelegramHTML"}}
                platform --> platform2{{"DiscordHTML"}}
            attributes --> chatName["chatName: String"]
                chatName --- chatName1("Name of the chat")
            attributes --> mainJsonType["type: String"]
                mainJsonType --> mainJsonType1{{"Direct"}}
                mainJsonType --> mainJsonType2{{"Group"}}
            attributes --> participants["participants: Array"]
                participants --> participant["participant: author"]
                    participant --> author
                    participant --- participant1("Participant author")
            attributes --> filePath["filePath: String"]
                filePath --- filePath1("Absolute path to file data was collected from")
        JSON --> messages["messages: Array"]
            messages --> message["message: Object?"]
                message --> id["id: String"]
                    id --- id1("Platform provided ID of message")
                message --> sequence["sequence: Integer"]
                    sequence --- sequence1("Sequence the message was read in")
                message --> timestamp["timestamp: String?"]
                    timestamp --- timestamp1("Timedate when message was sent")
                message --> messageType["type: String"]
                    messageType --> messageType1{{"Text"}}
                    messageType --> messageType2{{"Media"}}
                    messageType --> messageType3{{"System"}}
                    messageType --> messageType4{{"Call"}}
                message --> author["author: Object"]
                    author --> authorName["name: String?"]
                        authorName --- authorName1("Sender of message")
                    author --> authorType["type: String"]
                        authorType --> authorType1{{"Human"}}
                        authorType --> authorType2{{"Bot"}}
                        authorType --> authorType3{{"System"}}
                        authorType --> authorType4{{"Webhook"}}
                message --> body["body: String?"]
                    body --- body1("Text contents of message")
                message --> context["context: Object?"]
                    context -->contextTo["to: Integer?"]
                        contextTo --> contextTo1("Sequence of contextual message")
                    context --> contextText["text: String"]
                        contextText --> contextText1("Text of contextual message")
                message --> attachments["attachments: Array"]
                    subgraph attachmentsSubgraph[ ]
                        style attachmentsSubgraph fill:none,stroke:none
                        attachment --> attachmentMime["mime: String"]
                            attachmentMime --- attachmentMime1("MIME type of attachment")
                        attachment --> attachmentUrl["url: String"]
                            attachmentUrl --- attachmentUrl1("URL of attachment")
                    end
                    attachments --> attachment["attachment: Object?"]
                message --> reactions["reactions: Array"]
                    reactions --> reaction["reaction: Object?"]
                        reaction --> reactionName["name: String"]
                            reactionName --- reactionName1("Name of reaction")
                        reaction --> reactionAuthor["author: author"]
                            reactionAuthor --> author
                            reactionAuthor --- reactionAuthor1("Author of reaction")
                message --> callInfo["callInfo: Object?"]
                    callInfo --> callRecipient["recipient: String"]
                        callRecipient --> callRecipient1("Recipient of call")
                    callInfo --> callDuration["duration: Integer"]
                        callDuration --> callDuration1("Duration of call (in seconds)")
                    callInfo --> callIsSuccess["isSuccess: Boolean"]
                        callIsSuccess --> callIsSuccess1("Whether call was successful or not")
                    callInfo --> callIsOutgoing["isOutgoing: Boolean"]
                        callIsOutgoing --> callIsOutgoing1("Whether call was outgoing or not")
                %% To be implemented in next revision
                %% message --> forwarded["forwarded: message?"]
                %%     forwarded --> forwarded1("s")

        subgraph legend[ ]
            subroot["Legend"]
                style subroot fill:none,stroke:none
                subroot ~~~ root([Root Node])
                subroot ~~~ attribute["Attribute"]
                subroot ~~~ description("Description")
                subroot ~~~ enum{{"Enumerate"}}
        end
    end
